name: Publish

on: # publish when main branch changes
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Run npm clean-install
      run: npm clean-install
    - name: Run build
      run: npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        user_name: 'cffinit[bot]'
        user_email: 'cffinit[bot]@users.noreply.github.com'
        commit_message: ':robot: Update github.io page'
