name: zenodraft
on:
  # Trigger when you publish a release via GitHub's release page
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v3
        - name: Create a draft snapshot of your repository contents as a new
                version in collection 1404735 on Zenodo using metadata
                from repository file .zenodo.json
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          uses: zenodraft/action@0.10.0
          with:
            collection: 1404735
            metadata: .zenodo.json
            publish: true
            sandbox: false
            upsert-doi: true
            upsert-location: identifiers[0]
